### ISSUE TITLE
Mute/Snooze All - Double Icons

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/Cyrano#37]
If MUTE chosen  (or MUTE ALL) then there should be no more Snooze Icons in the list (or details).
If SNOOZE chosen  (or SNOOZE ALL) then there should be no more MUTE Icons in the list (or details).

**Comment by kevinlee85** [comment]
Hi Cj:
Does this my next milestone or a new bug should be fixed?

**Comment by cjcornell** [comment]
This should be fixed.

I am not sure, but I think the bug is from the way you set mute/snooze.  read the issue.  

It is quite odd - because there is no way both Mute and Snooze can be set at the same time.  So, I dont know if this is merely an icon-display issue or something odd, internally.

@dakshatechnologies please look too.  @kevinlee85 is setting snooze or mute  ... and the icons in the list display both ... this should never be the case (Mute and Snooze are mutually exclusive).

**Comment by kevinlee85** [comment]
Hi CJ:
I think this bug should be fixed by me.

**Comment by cjcornell** [comment]
Well, OK then ... fix it ... and move on to the next milestone so I can close your current one!

**Comment by kevinlee85** [comment]
Fix with new commit, and ftp file name is Cyrano_05_29_2015_01.apk.
Please test it.

**Comment by cjcornell** [comment]
Not quite fixed.
Please test a little more throughly sir ...
There is something clearly wrong, internally with the way Mute/Snooze are being reported to cyrano.

press: Snooze-All     (snooze icons correctly appear)
press: Mute-all  (mute icons correctly appear)
at this point, internally, all Friends should be marked as Mute (nothing snoozed)
Noe
press: Unmute all   (all icons and internal mute/snooze status should be cleared)
But
instead - the Snooze icons appear!
(see ... I just pressed Umute-all and all the snooze buttons appeared!)
----
Same problem occurs
with this sequence
Mute-All
Snooze-All
UnSnooze-All
(at this point there should be no icons... but instead there are all Mute icons)

Kevin - Just check on this internally
This is not a top priority right now ... your other milestone is top.

**Comment by kevinlee85** [comment]
Yes, sorry, i didn't test this sequence as you said.
I fix it and implement my next milestone with name as Cyrano_05_30_2015_01.apk.
I didn't upload it since i cannot access FTP anymore.
Please share the FTP password again.
Thank you very much.
Kevin Lee.
